# Generated by Django 6.0.3 on 2026-07-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
